### ISSUE TITLE
Cannot resolve support lib dependency

### ISSUE THREAD

**Issue by bluesliverx** [Centril/gradle-plugin-robospock#10]
The problem is that the URLs for the SDK m2repository/google repos are not actually URLs but are file paths.  This may work for some systems (linux maybe), but definitely doesn't work on Windows.

Replacing these with a true URL fixes "support library not found" problems.  I have a patch I will submit shortly.

**Comment by bluesliverx** [comment]
See also https://code.google.com/p/android/issues/detail?id=69270 for a google related bug.

**Comment by Centril** [comment]
Also good, merging =)
